### ISSUE TITLE
Add appropriate .gitignore file

### ISSUE THREAD

**Issue by NdubuisiJr** [Osoba001/AbstractedRabbitMQ#2]
Hi,
Great job abstracting the complexity of integrating rabbitMQ into your .Net backend. To avoid unnecessary conflicts when others contribute to this project, I think you should untrack the unwanted files in the project. You can refer to this [stackoverflow](https://stackoverflow.com/questions/1274057/how-do-i-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore) post on how to remove these files/folders from git.

**Comment by Osoba001** [comment]
Okay, noted thanks
